services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./tests
          target: /app/tests
        - action: sync
          path: ./alembic
          target: /app/alembic
        - action: rebuild
          path: ./requirements.txt
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/trademk1
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - QUESTDB_URL=postgresql://admin:quest@questdb:8812/qdb
      - BINANCE_API_URL=wss://stream.binance.com:9443
      - ALPACA_API_KEY=${ALPACA_API_KEY:-}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET:-}
      - ALPACA_BASE_URL=https://paper-api.alpaca.markets
    volumes:
      # Only mount files that aren't being watched
      - ./alembic.ini:/app/alembic.ini
      - ./docker/entrypoint.sh:/app/docker/entrypoint.sh
      - ./docker/entrypoint-temp.sh:/app/docker/entrypoint-temp.sh
      - ./docker/wait-for-it.sh:/app/docker/wait-for-it.sh
    entrypoint: ["/app/docker/entrypoint-temp.sh"]
    depends_on:
      - db
      - redis
      - questdb
    networks:
      - trademk1-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trademk1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trademk1-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - trademk1-network

  questdb:
    image: questdb/questdb:7.3.10
    container_name: trademk1-questdb
    ports:
      - "9000:9000"    # REST API and Web Console
      - "9009:9009"    # InfluxDB line protocol
      - "8812:8812"    # PostgreSQL wire protocol
    volumes:
      - questdb_data:/root/.questdb
    environment:
      - QDB_TELEMETRY_ENABLED=false
    networks:
      - trademk1-network

volumes:
  postgres_data:
  questdb_data:

networks:
  trademk1-network:
    driver: bridge