services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./tests
          target: /app/tests
        - action: rebuild
          path: ./requirements.txt
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trademk1
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      - db
      - redis
    networks:
      - trademk1-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trademk1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trademk1-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - trademk1-network

volumes:
  postgres_data:

networks:
  trademk1-network:
    driver: bridge