#!/bin/bash
# Configure trailing stops for the trading bot

echo "⚙️  Configuring Trailing Stops"
echo "============================="
echo ""
echo "Trailing stops automatically adjust your stop loss upward as"
echo "the price rises, locking in profits while giving room to grow."
echo ""
echo "Example configurations:"
echo "1. Conservative: 3% trail, activate after 2% profit"
echo "2. Moderate: 2% trail, activate after 1% profit (default)"
echo "3. Aggressive: 1% trail, activate immediately"
echo ""

# These would normally be set via the API
echo "Current configuration:"
echo "  • Enabled: Yes"
echo "  • Trail: 2% below highest price"
echo "  • Activates: After 1% profit"
echo ""
echo "This means:"
echo "  - Once a position gains 1%, trailing stop activates"
echo "  - Stop loss follows 2% below the highest price"
echo "  - If price drops 2% from peak, position is sold"
echo ""
echo "To change settings, use the API:"
echo "  curl -X PATCH http://localhost:8000/api/v1/autonomous/trailing-stop \\"
echo "    -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "    -d 'enabled=true&trail_percent=0.02&activate_after_profit=0.01'"
echo ""
echo "View active trailing stops:"
echo "  curl http://localhost:8000/api/v1/autonomous/trailing-stops \\"
echo "    -H 'Authorization: Bearer YOUR_TOKEN'"